# Generated by Django 5.1 on 2024-09-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=200, verbose_name='Номер телефона')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('answer', models.TextField(choices=[('yes', 'Да'), ('no', 'Нет')], default='no', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
    ]
