name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Add your test command here
        python -m unittest discover

    - name: Deploy to server
      env:
        SERVER: ${{ secrets.SERVER }}
        USER: ${{ secrets.USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $USER@$SERVER 'bash -s' < deploy.sh